### ISSUE TITLE
Remove price adjustment from calculateDemandbyType and calculateDemandByRegion

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO-State#11]
Having  a price adjustment here is duplicative and counter-intuitive. The price adjustment can easily be moved into a separate function and applied afterwards to these results. 

https://github.com/USEPA/USEEIO-State/blob/10193aefb5508dfa4df29d0bb230f2909bcda070/R/StateEEIOCalculations.R#L63-L79

https://github.com/USEPA/USEEIO-State/blob/10193aefb5508dfa4df29d0bb230f2909bcda070/R/StateEEIOCalculations.R#L109-L125

**Comment by bl-young** [comment]
That was actually my original thought as well. However, the price conversion is sector specific, so it has to be done before we sum across sectors (the `colSums` in the code above). So either we need to make the resulting matrix out of these functions be a single column for each vector (instead of the current approach which allows more than one vector for each column for a state).

**Comment by WesIngwersen** [comment]
Added a new function for dollar matrix price conversion. 
5d31301
